---  # начало документа
bot:
  api: "YOUR_TOKEN"
  ref: "speaker"

settings:
  number_of_tables: 20
  threshold_minutes: 15

admins:
  ids: [YOUR_ID, YOUR_ID]

meeting:
  zones:
    - "1 этаж"
    - "2 этаж"
    - "3 этаж"
  dates:
    - "29 ноября"
    - "30 ноября"
